version: '3.1'

services:
  app:
    build: .docker/php/
    container_name: hello_world_symfony_nginx_app
    user: 'www-data:www-data'
    environment:
      - ENVIROMENT=local
    volumes:
      - .:/var/www
    networks:
      - hello_world_symfony
    depends_on:
      - db
    
  nginx:
    build: .docker/nginx
    container_name: hello_world_symfony_nginx
    tty: true
    ports:
      - '80:80'
    volumes:
      - .:/var/www
    networks:
      - hello_world_symfony
    depends_on:
      - app
  
  db:
    build: .docker/mariadb
    platform: linux/amd64
    container_name: hello_world_symfony_mariadb
    ports:
      - '3306:3306'
    volumes:
      - .docker/mariadb/dbdata:/var/lib/mariadb
      - .docker/mariadb/scripts:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - hello_world_symfony

networks:
  hello_world_symfony:
    driver: bridge